# OpenAPI спецификация автоматически генерируется SpringDoc
# из аннотаций в контроллерах (@Operation, @ApiResponse и т.д.)
#
# Документация доступна по адресу:
# http://localhost:8080/swagger-ui.html
# http://localhost:8080/v3/api-docs